import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import getPagesPaths from './api/getPagesPaths'

const Home: NextPage = () => {
  const [pages, setPages] = React.useState([])
  useEffect(() => {
    async function getPagesPaths() {
      const { data } = await axios.get('/api/getPagesPaths')
      setPages(data.paths)
    }
    getPagesPaths()
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>next-various</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>
          <div className={styles.grid}>
            {pages.map((page) => (
              <a key={page} href={page} className={styles.card}>
                <h2>{page} &rarr;</h2>
              </a>
            ))}
          </div>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
